[package]
name = "celestia-url-reference"
version = "1.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[bin]]
name = "celestia-url-reference"
path = "src/main.rs"

[[test]]
name = "process"
path = "tests/process.rs"

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
