#!/usr/bin/env bash
# Copyright © 2026 @sudocelestia. All rights reserved.
#
# PROPRIETARY AND CONFIDENTIAL SOURCE CODE.
#
# No licence, permission or authorisation is granted to use, copy, modify,
# compile, execute, distribute, publish, sublicense or otherwise exploit this
# file, except to the limited extent unavoidably permitted by applicable law
# or GitHub's Terms of Service.
#
# See the LICENSE file at the repository root for the complete terms.

set -euo pipefail
export GOWORK=off

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=.github/scripts/verification/fixture.sh
source "$script_dir/fixture.sh"

main() (
root=$1
work_dir=$2
output=
status=0
fifo_pid=
trap '[[ -z "$fifo_pid" ]] || terminate_child "$fifo_pid"' EXIT
cat >"$work_dir/.git/info/exclude" <<'EOF'
/config-bin/
/lint-*/
/linter-policy/
/platform-bin/
/repo/
/rust/
/type-assertion/
EOF
if [[ "$(go env GOOS)" != windows ]] &&
  command -v mkfifo >/dev/null 2>&1; then
  printf '%s\n' 'package fixture' >"$work_dir/fifo.go"
  git -C "$work_dir" add -- fifo.go
  rm -- "$work_dir/fifo.go"
  mkfifo "$work_dir/fifo.go"
  (
    cd "$work_dir"
    "$work_dir/config-bin/sourcepolicy" suppressions \
      >"$work_dir/fifo-output" 2>&1
  ) &
  fifo_pid=$!
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    kill -0 "$fifo_pid" 2>/dev/null || break
    sleep 0.1
  done
  if kill -0 "$fifo_pid" 2>/dev/null; then
    terminate_child "$fifo_pid"
    printf 'source policy blocked while opening a FIFO\n' >&2
    return 1
  fi
  set +e
  wait "$fifo_pid"
  status=$?
  set -e
  fifo_pid=
  [[ "$status" -ne 0 ]] || {
    printf 'source policy accepted a FIFO\n' >&2
    return 1
  }
  grep -Fq 'source file is not a bounded regular file' \
    "$work_dir/fifo-output" || {
    printf 'source policy omitted the FIFO diagnostic\n' >&2
    return 1
  }
  rm -- "$work_dir/fifo.go" "$work_dir/fifo-output"
  git -C "$work_dir" reset -q -- fifo.go
fi
if git -C "$work_dir" ls-files -co --exclude-standard |
  grep -Eq '^((lint-|linter-policy|platform-bin|repo|rust|type-assertion)/)'; then
  printf 'coverage fixture inventory includes generated verifier state\n' >&2
  return 1
fi
{
  printf '%s\n' '// Code generated by fixture. DO NOT EDIT.'
  awk 'BEGIN { for (line = 0; line < 801; line++) print "// fixture" }'
} >"$work_dir/-generated.go"
set +e
output=$(cd "$work_dir" &&
  bash .github/scripts/policycheck.sh source-files 2>&1)
status=$?
set -e
[[ "$status" -eq 0 ]] || {
  printf 'policy check rejected an option-like generated filename:\n%s\n' \
    "$output" >&2
  return 1
}
rm -- "$work_dir/-generated.go"
awk 'BEGIN { for (line = 0; line < 5000; line++) print "// fixture" }' \
  >"$work_dir/oversized_test.go"
printf '%s' 'package fixture' >>"$work_dir/oversized_test.go"
set +e
output=$(cd "$work_dir" &&
  bash .github/scripts/policycheck.sh source-files 2>&1)
status=$?
set -e
[[ "$status" -ne 0 ]] || {
  printf 'policy check accepted a 5,001-line test file\n' >&2
  return 1
}
grep -Fq 'oversized_test.go: test file exceeds the 5,000-line maximum' \
  <<<"$output" || {
  printf 'policy check omitted the test-file limit diagnostic:\n%s\n' \
    "$output" >&2
  return 1
}
rm -- "$work_dir/oversized_test.go"
)

main "$@"
