// Copyright © 2026 @sudocelestia. All rights reserved.
//
// PROPRIETARY AND CONFIDENTIAL SOURCE CODE.
//
// No licence, permission or authorisation is granted to use, copy, modify,
// compile, execute, distribute, publish, sublicense or otherwise exploit this
// file, except to the limited extent unavoidably permitted by applicable law
// or GitHub's Terms of Service.
//
// See the LICENSE file at the repository root for the complete terms.

package main

import "slices"

func sourcePolicySplitFiles() []string {
	return slices.Clone(sourcePolicySplitInventory)
}

var sourcePolicySplitInventory = []string{
	"architecture_attempt_split_test.go",
	"architecture_attempt_split.go",
	"architecture_bounds_test.go",
	"architecture_documentation.go",
	"architecture_documentation_test.go",
	"architecture_evaluation.go",
	"architecture_fixture_evaluation_test.go",
	"architecture_fixtures_test.go",
	"architecture_imports_test.go",
	"architecture_imports.go",
	"architecture_integration_test.go",
	"architecture_inventory.go",
	"architecture_limits_test.go",
	"architecture_limits.go",
	"architecture_operation_split.go",
	"architecture_operation_split_test.go",
	"architecture_ownership.go",
	"architecture_ownership_test.go",
	"architecture_paths.go",
	"architecture_policy.go",
	"architecture_rust_test.go",
	"architecture_rust.go",
	"architecture_scripts_test.go",
	"architecture_scripts.go",
	"architecture_source_policy.go",
	"architecture_split_test.go",
	"architecture_split.go",
	"architecture_supervision_split.go",
	"architecture_supervision_split_test.go",
	"architecture_values.go",
	"architecture.go",
	"cargo_failures_test.go",
	"cargo_test.go",
	"cargo.go",
	"cargoconfig_failures_test.go",
	"cargoconfig_test.go",
	"cargoconfig.go",
	"doc.go",
	"executable_inventory_test.go",
	"executable_inventory.go",
	"go_policy_fixture_test.go",
	"gobuildtags.go",
	"gocgo_failures_test.go",
	"gocgo_test.go",
	"gocgo.go",
	"goexit.go",
	"goexit_dependency_test.go",
	"goexit_test.go",
	"gofallback.go",
	"goinspect_directives_test.go",
	"goinspect_source_test.go",
	"goinspect.go",
	"golangci.go",
	"goload_failures_test.go",
	"goload_replacement_test.go",
	"goload_test.go",
	"goload_timeout_test.go",
	"goload.go",
	"goskip_test.go",
	"goskip.go",
	"gotarget_constraints_test.go",
	"gotarget_selection_test.go",
	"gotarget_selector_test.go",
	"gotarget_test.go",
	"gotarget.go",
	"gotestmain_test.go",
	"gotestmain.go",
	"inventory_test.go",
	"inventory.go",
	"main_failures_test.go",
	"main_test.go",
	"main.go",
	"manifest_test.go",
	"manifest.go",
	"module_replacement.go",
	"rust_failures_test.go",
	"rust_test.go",
	"rustpolicy.go",
	"rustsyntax.go",
	"scan.go",
	"source_failures_test.go",
	"source_open_other.go",
	"source_open_unix.go",
	"source_test.go",
	"source.go",
	"suppression_comments_test.go",
	"suppression_test.go",
	"suppression.go",
	"testdata/architecture-v1.json",
	"testinventory_boundaries_test.go",
	"testinventory_test.go",
	"testinventory.go",
}
