// Copyright © 2026 @sudocelestia. All rights reserved.
//
// PROPRIETARY AND CONFIDENTIAL SOURCE CODE.
//
// No licence, permission or authorisation is granted to use, copy, modify,
// compile, execute, distribute, publish, sublicense or otherwise exploit this
// file, except to the limited extent unavoidably permitted by applicable law
// or GitHub's Terms of Service.
//
// See the LICENSE file at the repository root for the complete terms.

package main

import (
	"bytes"
	"errors"
	"io"
	"strings"
	"testing"
)

func TestSourceFileFindings(t *testing.T) {
	t.Parallel()
	files := map[string][]byte{
		"ordinary.go":        []byte("package fixture\n"),
		"coverage_test.go":   []byte("package fixture\n"),
		"helper.rs":          []byte("fn fixture() {}\n"),
		"large.c":            bytes.Repeat([]byte("\n"), 801),
		"boundary_test.cpp":  bytes.Repeat([]byte("\n"), 5000),
		"large_test.cpp":     bytes.Repeat([]byte("\n"), 5001),
		"generated.go":       []byte("// Code generated by fixture. DO NOT EDIT.\n" + strings.Repeat("\n", 900)),
		"ignored.txt":        []byte("ignored"),
		"unreadable_test.go": nil,
	}
	read := func(path string) ([]byte, error) {
		if path == "unreadable_test.go" {
			return nil, errors.New("unreadable")
		}
		return files[path], nil
	}
	findings := sourceFileFindings([]string{
		"ordinary.go", "coverage_test.go", "helper.rs", "large.c",
		"boundary_test.cpp", "large_test.cpp", "generated.go", "ignored.txt", "unreadable_test.go",
	}, read)
	joined := strings.Join(findings, "\n")
	for _, want := range []string{
		"coverage_test.go: use an intent-named residual coverage file",
		"helper.rs: vague accumulation filename is prohibited",
		"large.c: source file exceeds the 800-line exceptional maximum",
		"large_test.cpp: test file exceeds the 5,000-line maximum",
		"unreadable_test.go: unreadable",
	} {
		if !strings.Contains(joined, want) {
			t.Errorf("findings = %q, missing %q", joined, want)
		}
	}
	if strings.Contains(joined, "boundary_test.cpp") || strings.Contains(joined, "generated.go") ||
		strings.Contains(joined, "ignored.txt") {
		t.Fatalf("findings include excluded source: %q", joined)
	}
}

func TestRunSourceFileModeFailures(t *testing.T) {
	t.Parallel()
	inventoryFailure := func() ([]string, error) {
		return nil, errors.New("inventory failed")
	}
	if code := runSourceFileMode(io.Discard, inventoryFailure, nil); code != 1 {
		t.Fatalf("inventory failure status = %d, want 1", code)
	}
	if code := runSourceFileMode(failingWriter{}, inventoryFailure, nil); code != 1 {
		t.Fatalf("inventory diagnostic failure status = %d, want 1", code)
	}
	files := func() ([]string, error) { return []string{"coverage_test.go"}, nil }
	read := func(string) ([]byte, error) { return []byte("package fixture\n"), nil }
	if code := runSourceFileMode(failingWriter{}, files, read); code != 1 {
		t.Fatalf("finding diagnostic failure status = %d, want 1", code)
	}
}

func TestAllPolicyChecksOwnEveryVerdict(t *testing.T) {
	t.Parallel()
	checks := allPolicyChecks(nil, func() ([]string, error) { return nil, nil })
	names := make([]string, 0, len(checks))
	for _, check := range checks {
		names = append(names, check.name)
	}
	want := []string{
		"Architecture", "Manifests", "Test Skips", "Suppressions", "Source Files",
	}
	if strings.Join(names, "\n") != strings.Join(want, "\n") {
		t.Fatalf("policy checks = %v, want %v", names, want)
	}
}
